#define AUTO 1
#define DOUBLE 2
#define INT 3
#define STRUCT 4
#define BREAK 5
#define ELSE 6
#define LONG 7
#define SWITCH 8
#define CASE 9
#define ENUM 10
#define REGISTER 11
#define TYPEDEF 12
#define CHAR 13
#define EXTERN 14
#define RETURN 15
#define UNION 16
#define CONST 17
#define FLOAT 18
#define SHORT 19
#define UNSIGNED 20
#define CONTINUE 21
#define FOR 22
#define SIGNED 23
#define VOID 24
#define DEFAULT 25
#define GOTO 26
#define SIZEOF 27
#define VOLATILE 28
#define DO 29
#define IF 30
#define STATIC 31
#define WHILE 32
#define COMMENT 33
#define IDENTIFIER 34
#define STRING 35
#define UNARYOPERATOR 36
#define LOGICALOPERATOR 37
#define ARITHEMATICOPERATOR 38
#define RELATIONALOPERATOR 39
#define BITWISEOPERATOR 40
#define PARANTHESES 41
#define ASSIGNMENTOPERATOR 42
#define NEWLINE 43
#define TAB 44
#define SPACE 45
#define OTHERSYMBOLS 46
#define ERROR 47
